### ISSUE TITLE
Latest version not working

### ISSUE THREAD

**Issue by b-rohit** [mindsphere/mindconnect-nodejs#105]
**Describe the bug**
The mindconnect-nodejs version 3.6.1 is not working

**To Reproduce**
1. install latest version
npm install -g @mindconnect/mindconnect-nodejs@latest
2. Run mc command
mc --help

**Expected behavior**
should show help for mc command

**Screenshots**

```
$ mc --help
internal/util.js:209
    throw new errors.TypeError('ERR_INVALID_ARG_TYPE', 'original', 'function');
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "original" argument must be of type function
    at Object.promisify (internal/util.js:209:11)
    at Object.<anonymous> (/home/rohit/.nvm/versions/node/v8.9.4/lib/node_modules/@mindconnect/mindconnect-nodejs/dist/src/cli/commands/mc-download-file.js:19:29)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/rohit/.nvm/versions/node/v8.9.4/lib/node_modules/@mindconnect/mindconnect-nodejs/dist/src/cli/mc.js:13:28)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
```

**Desktop (please complete the following information):**
 - OS : "16.04.6 LTS (Xenial Xerus)"
 - Node : v8.9.4
 - npm : 6.0.1

**Comment by sn0wcat** [comment]
Your node version is very old , could you please update node to LTS and try again?

**Comment by b-rohit** [comment]
thanks. I installed node v12.13.1. It works fine. I get following error when I try to onboard an agent.
```
$ mc onboard -c ./agentconfig.json
...Retry no 1 for OnBoard operation.
...Retry no 2 for OnBoard operation.

Network error occured Unauthorized {"error":"token_validation_failed","error_description":"[cf1045938bd24e138ee786f90247428f]"}
```
[https://github.com/mindsphere/mindconnect-nodejs/issues/82](url)
